/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.MontadoraController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Montadora;

/**
 *
 * @author varcal
 */
public class FrmMontadoraDetalhes extends javax.swing.JInternalFrame {

    JDesktopPane _internalPrincipal;
    MontadoraController _controller;
    
    public FrmMontadoraDetalhes(JDesktopPane internalPrincipal) {
        initComponents();
        this.setLocation(280, 100);
        _internalPrincipal = internalPrincipal;
        _controller = new MontadoraController();
        carregarTabela("Ativos","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAcoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridMontadoras = new javax.swing.JTable();
        cbSituacao = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setTitle("Detalhes Montadoras");
        setPreferredSize(new java.awt.Dimension(800, 544));

        pnlAcoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAcoesLayout = new javax.swing.GroupLayout(pnlAcoes);
        pnlAcoes.setLayout(pnlAcoesLayout);
        pnlAcoesLayout.setHorizontalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAcoesLayout.setVerticalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        gridMontadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridMontadoras.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(gridMontadoras);
        if (gridMontadoras.getColumnModel().getColumnCount() > 0) {
            gridMontadoras.getColumnModel().getColumn(0).setResizable(false);
            gridMontadoras.getColumnModel().getColumn(0).setPreferredWidth(20);
            gridMontadoras.getColumnModel().getColumn(1).setResizable(false);
            gridMontadoras.getColumnModel().getColumn(1).setPreferredWidth(80);
            gridMontadoras.getColumnModel().getColumn(2).setResizable(false);
            gridMontadoras.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativos", "Inativos" }));

        btnPesquisar.setText("...");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPesquisar)
                    .addComponent(cbSituacao)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
        chamarFormMontadoraCadastro(AcaoNaTela.Inserir, null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        int linhaSelecionada  = gridMontadoras.getSelectedRow();
        
        if(linhaSelecionada <= 0){
            JOptionPane.showMessageDialog(null, "Nenhuma montadora foi selecionda.", "INFORMAÇÔES", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Montadora montadora = retornaObjetoLinhaSelecionada(linhaSelecionada);
      
        chamarFormMontadoraCadastro(AcaoNaTela.Editar, montadora);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
         int linhaSelecionada  = gridMontadoras.getSelectedRow();
        
        if(linhaSelecionada <= 0){
            JOptionPane.showMessageDialog(null, "Nenhuma montadora foi selecionda.", "INFORMAÇÔES", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Montadora montadora = retornaObjetoLinhaSelecionada(linhaSelecionada);
        
        chamarFormMontadoraCadastro(AcaoNaTela.Detalhes, montadora);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    
        int linhaSelecionada  = gridMontadoras.getSelectedRow();
        
        if(linhaSelecionada <= 0){
            JOptionPane.showMessageDialog(null, "Nenhuma montadora foi selecionda.", "INFORMAÇÔES", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Montadora montadora = retornaObjetoLinhaSelecionada(linhaSelecionada);

        int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "PERGUNTA", JOptionPane.YES_NO_CANCEL_OPTION);      
        if(result == JOptionPane.YES_NO_OPTION){
            try{
                _controller.excluir(montadora);               
                removerLinha(linhaSelecionada);
            }catch(SQLException ex){
                 JOptionPane.showMessageDialog(null, "Erro ao tentar excluir a montadora", "ERRO", JOptionPane.ERROR_MESSAGE);
            }           
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String situacao = cbSituacao.getSelectedItem().toString();
        String pesquisa = txtPesquisar.getText().trim();  
        while (gridMontadoras.getModel().getRowCount() > 0) {  
           ((DefaultTableModel) gridMontadoras.getModel()).removeRow(0);  
        }     
        carregarTabela(situacao, pesquisa);               
    }//GEN-LAST:event_btnPesquisarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbSituacao;
    private javax.swing.JTable gridMontadoras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables


    private void chamarFormMontadoraCadastro(AcaoNaTela acao, Montadora montadora) {
        FrmMontadoraCadastro frm = new FrmMontadoraCadastro(_internalPrincipal,acao, montadora);
        this.dispose();
        _internalPrincipal.add(frm);
        frm.setVisible(true);
    }
    
    private void carregarTabela(String situacao, String pesquisa){
        
        ArrayList<Montadora> montadoras = new ArrayList<Montadora>();
        
        try{
            montadoras = _controller.selecionarTodosAtivosInativos(situacao ,pesquisa);
                     
            if(montadoras == null){
                JOptionPane.showMessageDialog(null, "Nenhuma montadora cadastrada", "INFORMAÇÕES", JOptionPane.INFORMATION_MESSAGE);
            }
            
            DefaultTableModel table = (DefaultTableModel) gridMontadoras.getModel();
            
            for(Montadora m: montadoras){
                table.addRow(new Object[]{m.getId(), m.getNome(),m.isAtivo()? "Ativo" : "Inativo"});
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Não foi possível carregas as informações Detalhes: "+ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void removerLinha(int linhaSelecionada){
        DefaultTableModel table = (DefaultTableModel) gridMontadoras.getModel();
        
        table.removeRow(linhaSelecionada);
    }
        
    private Montadora retornaObjetoLinhaSelecionada(int linhaSelecionada){
        
        int id =  (Integer)gridMontadoras.getValueAt(linhaSelecionada, 0);
        String nome = (String)gridMontadoras.getValueAt(linhaSelecionada, 1);
        boolean ativo = (String)gridMontadoras.getValueAt(linhaSelecionada, 2) == "Ativo";                          
        Montadora montadora = new Montadora(id, nome, ativo);    
        
        return montadora;
    }
}
