/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ModeloController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.plaf.DesktopPaneUI;
import javax.swing.table.DefaultTableModel;
import models.Modelo;
import models.Montadora;

/**
 *
 * @author varcal
 */
public class FrmModeloDetalhes extends javax.swing.JInternalFrame {

    JDesktopPane _internalPrincipal;
    ModeloController _modeloController;
    
    /*
     * Creates new form FrmDetalhesModelo
     */
    public FrmModeloDetalhes(JDesktopPane internalPrincipal) {
        initComponents();
        this.setLocation(280, 100);
        _internalPrincipal = internalPrincipal;
        _modeloController = new ModeloController();
        
        carregarTabela("Ativos","");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAcoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridModelo = new javax.swing.JTable();
        cbSituacao = new javax.swing.JComboBox<>();

        setTitle("Detalhes Modelos");

        pnlAcoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAcoesLayout = new javax.swing.GroupLayout(pnlAcoes);
        pnlAcoes.setLayout(pnlAcoesLayout);
        pnlAcoesLayout.setHorizontalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetalhes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        pnlAcoesLayout.setVerticalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnPesquisar.setText("...");

        gridModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Modelo", "Montadora", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gridModelo);
        if (gridModelo.getColumnModel().getColumnCount() > 0) {
            gridModelo.getColumnModel().getColumn(0).setResizable(false);
            gridModelo.getColumnModel().getColumn(1).setResizable(false);
            gridModelo.getColumnModel().getColumn(2).setResizable(false);
        }

        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ativos", "Inativos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSituacao)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed
  
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        chamarFormModeloCadastro(AcaoNaTela.Inserir, null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        int linhaSelecionada  = gridModelo.getSelectedRow();
        
        if(linhaSelecionada <= 0){
            JOptionPane.showMessageDialog(null, "Nenhum modelo foi seleciondo.", "INFORMAÇÔES", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int id =  (Integer)gridModelo.getValueAt(linhaSelecionada, 0);
       
        Modelo modelo = null;
        try {
            modelo = _modeloController.buscarPorId(id);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Ocorreu um erro ao tentar visualizar um model.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        chamarFormModeloCadastro(AcaoNaTela.Editar, modelo);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        int linhaSelecionada  = gridModelo.getSelectedRow();
        
        if(linhaSelecionada <= 0){
            JOptionPane.showMessageDialog(null, "Nenhum modelo foi seleciondo.", "INFORMAÇÔES", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int id =  (Integer)gridModelo.getValueAt(linhaSelecionada, 0);
       
        Modelo modelo = null;
        try {
            modelo = _modeloController.buscarPorId(id);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Ocorreu um erro ao tentar visualizar um model.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }         
        chamarFormModeloCadastro(AcaoNaTela.Detalhes, modelo);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada  = gridModelo.getSelectedRow();
        
        if(linhaSelecionada <= 0){
            JOptionPane.showMessageDialog(null, "Nenhum modelo foi seleciondo.", "INFORMAÇÔES", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int id =  (Integer)gridModelo.getValueAt(linhaSelecionada, 0);
        try {
            Modelo modelo = _modeloController.buscarPorId(id);
            int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "PERGUNTA", JOptionPane.YES_NO_CANCEL_OPTION);      
            if(result == JOptionPane.YES_NO_OPTION){
                _modeloController.excluir(modelo);               
                removerLinha(linhaSelecionada);                       
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar excluir a montadora", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
              
        
    }//GEN-LAST:event_btnExcluirActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbSituacao;
    private javax.swing.JTable gridModelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    private void chamarFormModeloCadastro(AcaoNaTela acao, Modelo modelo) {
        FrmModeloCadastro frm = new FrmModeloCadastro(_internalPrincipal,acao, modelo);
        this.dispose();
        _internalPrincipal.add(frm);
        frm.setVisible(true);
    }
    
    private void carregarTabela(String situacao, String pesquisa){
        
        ArrayList<Modelo> modelos = new ArrayList<Modelo>();
        
        try{
            modelos = _modeloController.selecionarTodosAtivosInativos(situacao ,pesquisa);
                     
            if(modelos == null){
                JOptionPane.showMessageDialog(null, "Nenhum modelo cadastrada", "INFORMAÇÕES", JOptionPane.INFORMATION_MESSAGE);
            }
            
            DefaultTableModel table = (DefaultTableModel) gridModelo.getModel();
            
            for(Modelo m: modelos){
                table.addRow(new Object[]{m.getId(), m.getNome(), m.Montadora.getNome(), m.isAtivo()? "Ativo" : "Inativo"});
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Não foi possível carregas as informações Detalhes: "+ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void removerLinha(int linhaSelecionada){
        DefaultTableModel table = (DefaultTableModel) gridModelo.getModel();
        
        table.removeRow(linhaSelecionada);
    }
}
